// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    sessionSecret: 'Random string',
    oauthConsumerKey: 'Twitter OAuth Consumer key',
    oauthConsumerSecret: 'Twitter OAuth Consumer secret',
    firebaseSecret: 'Firebase Secret',
    originUrl: 'http://example.com',
    callbackUrl: 'http://example.com'
  };

}).call(this);
